### ISSUE TITLE
visualization: menu overlapping main window

### ISSUE THREAD

**Issue by daslerr** [thor-project/dashboard#12]
The menu seems to be overlapping the main window on some browsers. So far, it's happened in Chrome on the Mac. Not sure about others yet.

![image](https://cloud.githubusercontent.com/assets/3181623/11815601/ad7cf8b0-a34c-11e5-923a-a961139f2bd7.png)

**Comment by eamonnmag** [comment]
Should be fixed in the latest update.

**Comment by daslerr** [comment]
It's still happening. It seems to only be happening when you zoom out or use a monitor with a higher resolution. As it tries to fit more content on the screen, the content pane gets pushed under the menu and sticks there. It's fine when it's zoomed in.
